package logicamente.parser;

import java.io.StringReader;

import logicamente.formulas.Formula;

/**
 * A parser for classical propositional logic formulas. A wrapper for the class
 * generated by the CUP parser generator.
 * 
 * @author Turma Métodos Ágeis PPGCA UTFPR 2010
 * 
 */
public class Parser {

	private StringReader reader;
	private SyntaxTreeLexer lexer;
	private SyntaxTreeParser generatedParser;

	/**
	 * Instantiates a parser
	 */
	public Parser() {
		lexer = new SyntaxTreeLexer(reader);
		generatedParser = new SyntaxTreeParser(lexer);
	}

	/**
	 * Parses a string
	 * 
	 * @param input
	 *            string
	 * @return an object of the class ParseResult
	 */
	public ParseResult parse(String string) {
		reader = new StringReader(string);
		lexer.yyreset(reader);

		ParseResult result = new ParseResult();

		try {
			result.setFormula((Formula) generatedParser.parse().value);
			result.setParseCorrect(true);
		} catch (Error e) {
			result.setFormula(null);
			result.setParseCorrect(false);
			return result;
		} catch (Exception e) {
			result.setFormula(null);
			result.setParseCorrect(false);
			return result;
		}

		return result;
	}

}
