
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 28 03:01:45 BRT 2010
//----------------------------------------------------

package logicamente.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 3;
  public static final int EOF = 0;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int IMPLIES = 5;
  public static final int RPAREN = 7;
  public static final int NEG = 2;
  public static final int LPAREN = 6;
  public static final int OR = 4;
}

